http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  ambilProvinsi:
    host: 'localhost'
    paths: '/serviceA'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  ManajemenWilayah:
    url: 'http://localhost:3001'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # default:
  #   apiEndpoints:
  #     - api
  #   policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      # - proxy:
      #     - action:
      #         serviceEndpoint: httpbin 
      #         changeOrigin: true
  pipelineManajemenWilayah:
    provinsi:
      - ambilProvinsi
    policies:
      - proxy:
          - action:
              serviceEndpoint: ManajemenWilayah
              changeOrigin: true
