http:
  port: 8080
admin:
  port: 9876
  host: localhost

# Service Endpoints
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
# Manajemen Wilayah
  manajemenWilayah:
    url: 'https://5bb9-112-78-133-82.ngrok-free.app'
# Developer
  Developer: 
    url: 'https://9329-112-78-133-82.ngrok-free.app'


# API ENDPOINT
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
# Manajemen Wilayah
  # GET ENDPOINTS
  ambilProvinsi:
    paths: '/manajemenWilayah/ambilProvinsi'
  ambilWilayah:
    paths: '/manajemenWilayah/ambilWilayah'
  ambilKota:
    paths: '/manajemenWilayah/ambilKota'
  ambilDaftarManajer:
    paths: '/manajemenWilayah/ambilDaftarManajer'
  ambilManajerDariId:
    paths: '/manajemenWilayah/ambilManajer/:id_manajer'
  ambilManajerDariWilayah:
    paths: '/manajemenWilayah/ambilManajerDariWilayah/:id_wilayah'
  ambilManajerDariKota:
    paths: '/manajemenWilayah/ambilManajerDariKota/:id_kota'
  ambilKotaDariId:
    paths: '/manajemenWilayah/ambilKotaDariId/:id_kota'
  ambilWilayahDariProvinsi:
    paths: '/manajemenWilayah/ambilWilayahDariProvinsi/:id_provinsi'
  ambilKotaDariWilayah:
    paths: '/manajemenWilayah/ambilKotaDariWilayah/:id_wilayah'

  # POST ENDPOINTS
  tambahProvinsi:
    paths: '/manajemenWilayah/tambahProvinsi'
  tambahWilayah:
    paths: '/manajemenWilayah/tambahWilayah'
  tambahKota:
    paths: '/manajemenWilayah/tambahKota'
  tambahManajer:
    paths: '/manajemenWilayah/tambahManajer'

  # PATCH ENDPOINTS
  ubahProvinsi:
    paths: '/manajemenWilayah/ubahProvinsi/:id_provinsi'
  ubahWilayah:
    paths: '/manajemenWilayah/ubahWilayah/:id_wilayah'
  ubahKota:
    paths: '/manajemenWilayah/ubahKota/:id_kota'
  ubahManajer:
    paths: '/manajemenWilayah/ubahManajer/:id_manajer'

  # DELETE ENDPOINTS
  hapusProvinsi:
    paths: '/manajemenWilayah/hapusProvinsi/:id_provinsi'
  hapusWilayah:
    paths: '/manajemenWilayah/hapusWilayah/:id_wilayah'
  hapusKota:
    paths: '/manajemenWilayah/hapusKota/:id_kota'
  hapusManajer:
    paths: '/manajemenWilayah/hapusManajer/:id_manajer'

# Developer
  # buat developer
  buatDeveloper:
    paths: '/developer/buatDeveloper'
  ambilSemuaDeveloper:
    paths: '/developer/ambilSemuaDeveloper'
  ambilDataDeveloper:
    paths: '/developer/ambilDataDeveloper/:id'
  ambilDeveloperByAdmin:
    paths: '/developer/ambilDeveloperByAdmin/:admin_id'
  cariDeveloper:
    paths: '/developer/cariDeveloper'
  editDeveloper:
    paths: '/developer/editDeveloper/:id'
  tambahPropertiDeveloper:
    paths: '/developer/tambahPropertiDeveloper/:id'
  hapusDeveloper:
    paths: '/developer/hapusDeveloper/:id'
  hapusPropertiDeveloper:
    paths: '/developer/hapusPropertiDeveloper/:id'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  
  # Manajemen Wilayah     
  # GET PIPELINES
  ambilProvinsi:
    apiEndpoints:
      - ambilProvinsi
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilWilayah:
    apiEndpoints:
      - ambilWilayah
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilKota:
    apiEndpoints:
      - ambilKota
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilDaftarManajer:
    apiEndpoints:
      - ambilDaftarManajer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilWilayahDariProvinsi:
    apiEndpoints:
      - ambilWilayahDariProvinsi
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilKotaDariWilayah:
    apiEndpoints:
      - ambilKotaDariWilayah
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilKotaDariId:
    apiEndpoints:
      - ambilKotaDariId
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilManajerDariId:
    apiEndpoints:
      - ambilManajerDariId
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilManajerDariWilayah:
    apiEndpoints:
      - ambilManajerDariWilayah
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ambilManajerDariKota:
    apiEndpoints:
      - ambilManajerDariKota
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
    

  # POST PIPELINES
  tambahProvinsi:
    apiEndpoints:
      - tambahProvinsi
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  tambahWilayah:
    apiEndpoints:
      - tambahWilayah
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  tambahKota:
    apiEndpoints:
      - tambahKota
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true

  # PATCH PIPELINES
  ubahProvinsi:
    apiEndpoints:
      - ubahProvinsi
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'PATCH'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ubahWilayah:
    apiEndpoints:
      - ubahWilayah
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'PATCH'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ubahKota:
    apiEndpoints:
      - ubahKota
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'PATCH'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  ubahManajer:
    apiEndpoints:
      - ubahManajer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'PATCH'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true

  # DELETE PIPELINES
  hapusProvinsi:
    apiEndpoints:
      - hapusProvinsi
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'DELETE'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  hapusWilayah:
    apiEndpoints:
      - hapusWilayah
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'DELETE'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  hapusKota:
    apiEndpoints:
      - hapusKota
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'DELETE'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true
  hapusManajer:
    apiEndpoints:
      - hapusManajer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'DELETE'
      - proxy:
          - action:
              serviceEndpoint: manajemenWilayah
              changeOrigin: true

  # Developer
  buatDeveloper:
    apiEndpoints:
      - buatDeveloper
    policies:
      - cors:
        - action: 
            action:
              origin: '*'
              method: POST
      - proxy:
        - action:
            serviceEndpoint: Developer
            changeOrigin: true

  ambilSemuaDeveloper:
    apiEndpoints:
      - ambilSemuaDeveloper
    policies: 
      - proxy: 
        - action:
            serviceEndpoint: Developer
            changeOrigin: true
  
  ambilDataDeveloper:
    apiEndpoints:
      - ambilDataDeveloper
    policies:
      - cors:
        - action: 
            origin: '*'
            method: GET
      - proxy: 
        - action:
            serviceEndpoint: Developer
            changeOrigin: true

  ambilDeveloperByAdmin:
    apiEndpoints: 
      - ambilDeveloperByAdmin
    policies:
      - cors:
        - action:
            origin: '*'
            method: GET
      - proxy:
        - action:
            serviceEndpoint: Developer
            changeOrigin: true

  cariDeveloper:
    apiEndpoints:
      - cariDeveloper
    policies:
      - cors: 
        - action:
            origin: '*'
            method: GET
      - proxy:
        - action:
            serviceEndpoint: Developer
            changeOrigin: true
   
  editDeveloper:
    apiEndpoints:
      - editDeveloper
    policies:
      - cors:
        - action: 
            origin: '*'
            method: PATCH
      - proxy:
        - action: 
            serviceEndpoint: Developer
            changeOrigin: true   

  tambahPropertiDeveloper:
    apiEndpoints:
      - tambahPropertiDeveloper
    policies:
      - cors: 
        - action:
            origin: '*'
            method: PATCH
      - proxy: 
        - action:
            serviceEndpoint: Developer
            changeOrigin: true
    
  hapusDeveloper:
    apiEndpoints:
      - hapusDeveloper
    policies:
      - cors: 
        - action:
            origin: '*'
            method: DELETE
      - proxy:
        - action:
            serviceEndpoint: Developer
            changeOrigin: true
    
  hapusPropertiDeveloper:
    apiEndpoints:
      - hapusPropertiDeveloper
    policies:
      - cors:
        - action:
            origin: '*'
            method: DELETE
      - proxy:
        - action:
            serviceEndpoint: Developer
            changeOrigin: true  
